# Generated by Django 5.0.2 on 2024-03-04 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teacher_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
