# Generated by Django 5.0.2 on 2024-03-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentcourseenrollnment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrollnment',
            old_name='enroolled_time',
            new_name='enrolled_time',
        ),
    ]
