# Generated by Django 5.0.2 on 2024-03-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_studentassignment_options_studentstatusupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentstatusupdate',
            options={'verbose_name_plural': '18. Student Status Updates'},
        ),
        migrations.CreateModel(
            name='TeacherStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress')], default='PENDING', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates_teacher', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '19. Teacher Status Updates',
            },
        ),
    ]
